[package]
name = "dump-schedule"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "*"
curl = "*"

[profile.release]
debug = 0
opt-level = 'z'
lto = true
codegen-units = 1
strip = true

